name: "Hello World"

on:
  schedule:
    - cron: '40 01 * * *'

jobs:
  greet:
    name: greet
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0
    - run: date
    - run: ./commit_script.sh 
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}